### ISSUE TITLE
Criação do dataset

### ISSUE THREAD

**Issue by italovinicius18** [deeplearningunb/PoemGenerator#2]
A partir do dados coletados no web scraping, existe a necessidade de transformar estes dados não estruturados em algum modelo estruturado, como um CSV, sendo facilmente manipulado pelas bibliotecas de machine learning ou manipulação de dados como o Pandas

**Comment by IanFPFerreira** [comment]
Depois de chamada a função que realiza o web scraping do site: [pensador](https://www.pensador.com/poemas/) - é retornado três listas, que são o texto do poema, o autor do poema, e a url de onde o poema foi tirado, no intuito desse último servir como uma maneira de conseguirmos rastrear as informações que extraímos. Depois disso, passamos essas listas como valores para um dataset com três colunas: 'Authors', 'Poems' e 'Page' - e fizemos o tratamento desses dados, retirando informações que definimos como não importantes, como por exemplo, a existência do '\n' na coluna 'Authors', e por fim exportamos esse dataset que possui 3 colunas e 920 linhas para um arquivo no formato .csv, que é o arquivo [authors_poems.csv](https://github.com/deeplearningunb/PoemGenerator/blob/develop/data/authors_poems.csv).
