### ISSUE TITLE
Definição do modelo preditivo

### ISSUE THREAD

**Issue by italovinicius18** [deeplearningunb/PoemGenerator#3]
A partir da estrutura dos dados precisamos escolher quais métodos e ferramentas vamos utilizar para a geração do poemas, podendo ser, previamente alguma das bibliotecas abaixo:

- SpaCy
- Tensorflow/Keras
- FastAI

**Comment by AlvaroLeles** [comment]
Inicialmente tentamos utilizar FastAI para criar o modelo preditivo, mas após algumas dificuldades, mudamos nossa abordagem para utilização do Tensorflow/Keras, biblioteca essa em que já tínhamos um pouco mais de domínio, criando assim, nosso modelo.
